# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vss_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vss_data.proto',
  package='proto_struct',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0evss_data.proto\x12\x0cproto_struct\")\n\x07VssData\x12\x10\n\x08vss_code\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\rb\x06proto3'
)




_VSSDATA = _descriptor.Descriptor(
  name='VssData',
  full_name='proto_struct.VssData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vss_code', full_name='proto_struct.VssData.vss_code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto_struct.VssData.data', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['VssData'] = _VSSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VssData = _reflection.GeneratedProtocolMessageType('VssData', (_message.Message,), {
  'DESCRIPTOR' : _VSSDATA,
  '__module__' : 'vss_data_pb2'
  # @@protoc_insertion_point(class_scope:proto_struct.VssData)
  })
_sym_db.RegisterMessage(VssData)


# @@protoc_insertion_point(module_scope)
